#include <iostream>
#include <fstream>
#include <string>
#include<stdio.h>
#include "limit.h"
using namespace std;
bool is_file_exist(const char *fileName)
{
    ifstream infile(fileName);
    return infile.good();
}

void manual_prog()
{
  Int_t i,j,k,n=5,m=5,o=6;
  // set n,m,o to be cardinality of set of energy,mass, and charge
  string hist,filename,canvasname,canvas, histname,sav_file,
  //set the energy, charge and mass...
  energy[5]={"1","100","500","1000","10000"},
  charge[6]={"1","0.1","0.01","0.005","0.002","0.0001"},
  mass="105*MeV";

  Double_t eng[n],c=0,mean[5][5];


  cout<<"Taking the data from limit.h"<<endl;





  TH1D * Hist[n][o];
  ifstream infile;
  for(i=0;i<5;i++)
  {
    for(j=0;j<m;j++)
    {
      histname = "For Charge = "+charge[j];
      filename="Muon_Stable=true_Energy="+energy[i]+"MeV_Mass_"+mass+"_Charge="+charge[j]+".txt";
      hist = histname+";Deposited Energy in  MeV; Counts";
      // cout<<hist<<"\t"<<histname<<endl;
      Hist[i][j]= new TH1D(histname.c_str(),hist.c_str(),1000,limit[i][j][0],limit[i][j][1]); //limit is defined in limit.h generated by run_once.C


      // Checking for filename...
      if(is_file_exist(filename.c_str()))
      {
        // cout<<filename<<" FOUND!"<<endl;
        infile.open(filename.c_str());

        while(!infile.eof())
           {
              infile >> c;
              // cout<<c<<endl;
              Hist[i][j]->Fill(c);

            }
        infile.close();

      }
      else
      {
        cout<<endl<<"Sorry, "<<filename<<" doesn't exist"<<endl;
        // mean[i][j]=0;
      }
    }
  }

  // Plotting energy spectrums...
  TCanvas* can[5];
  for(i=0;i<5;i++)
  {
  canvasname = "Energy="+energy[i]+"MeV with Mass="+mass;
  canvas = "Incidient Energy of "+energy[i]+"MeV";
  can[i] = new TCanvas(canvasname.c_str(),canvas.c_str(),800,600);
  can[i]->Divide(2,3);
  for(j=0;j<5;j++)
  {
    can[i]->cd(j+1);
    Hist[i][j]->Fit("landau");
    Hist[i][j]->Draw();
    gPad->SetLogy();
  }
  canvasname+=".png";
  can[i]->Print(canvasname.c_str());
}

}
